apiVersion: v1
kind: Service
metadata:
  name: slide-backend-service
  namespace: slide
spec:
  selector:
    app: slide-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
