apiVersion: v1
kind: Service
metadata:
  name: slide-frontend-service
  namespace: slide
spec:
  selector:
    app: slide-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      
  type: LoadBalancer
