# Generated by Django 5.1.3 on 2024-11-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_friendsrequest_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='sent_to',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='sent_by',
            new_name='sender',
        ),
    ]
